### ISSUE TITLE
Неполная/неправильная инструкция по установке

### ISSUE THREAD

**Issue by Sogl** [dudeonthehorse/Email#40]
Понадобилось снова отверстать e-mail, поэтому вновь обратился к этому проекту.
Читаю инструкцию:
```
1. Download Kilogram
2. Go to project_name folder using $ ls or $ dir command
3. Run $ gulp to launch builder and project watcher
4. Have fun!
```

Скачал. Перешел в `projects\kilogram` и запустил `gulp`:
```
C:\projects\kilogram-dev\projects\kilogram>gulp
[10:10:04] Local gulp not found in C:\projects\kilogram-dev\projects\kilogram
[10:10:04] Try running: npm install gulp
```

Сначала я подумал, что у меня не установлен gulp глобально, поэтому:
```
C:\projects\kilogram-dev\projects\kilogram>yarn global add gulp
yarn global v0.20.3
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "0.21.3" while you're on "0.20.3".
info To upgrade, run the following command:
$ npm upgrade --global yarn
success Installed "gulp@3.9.1" with binaries:
      - gulp
warning No license field
Done in 4.60s.

C:\projects\kilogram-dev\projects\kilogram>gulp -v
[10:10:32] CLI version 3.9.1

C:\projects\kilogram-dev\projects\kilogram>gulp
[10:10:35] Local gulp not found in C:\projects\kilogram-dev\projects\kilogram
[10:10:35] Try running: npm install gulp
```

Тот же результат.
Сделал то, что от меня просит консоль:
```
C:\projects\kilogram-dev\projects\kilogram>npm install gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
kilogram@1.1.0 C:\projects\kilogram-dev
.....
....
<<<<куча зависимостей>>>>
....
....
```

В итоге папка `node_modules` создалась не в той папке, где я запускал команду, а в корне проекта. Первый раз такое вижу :smile: 

Снова пробуем, теперь с другой ошибкой:
```
C:\projects\kilogram-dev\projects\kilogram>gulp
module.js:328
    throw err;
    ^

Error: Cannot find module 'require-dir'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\projects\kilogram-dev\projects\kilogram\gulpfile.js:1:80)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

Ага! Зависимости не все установились. Также наконец заметил в корне проекта `package.json`.
Делаем правильно:
````
C:\projects\kilogram-dev\projects\kilogram>cd ..

C:\projects\kilogram-dev\projects>cd ..

C:\projects\kilogram-dev>yarn
yarn install v0.20.3
info No lockfile found.
warning kilogram@1.1.0: "dependencies" has dependency "gulp-concat" with range "2.6.0" that collides with a dependency in "devDependencies" of the same name with version "^2.6.0"
warning kilogram@1.1.0: "dependencies" has dependency "gulp-inline-css" with range "3.0.0" that collides with a dependency in "devDependencies" of the same name with version "^3.0.0"
[1/4] Resolving packages...
warning gulp-nunjucks-render > nunjucks@1.3.4: potential XSS vulnerability in autoescape mode, and with escape filter was fixed in v2.4.3
warning gulp-nunjucks-render > nunjucks > chokidar > readdirp > graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp-nunjucks-render > nunjucks > chokidar > readdirp > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp-nunjucks-render > through2 > xtend > object-keys@0.4.0:
warning browser-sync > localtunnel > request > node-uuid@1.4.7: use uuid module instead
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "win32" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
warning fsevents@0.3.8: The platform "win32" is incompatible with this module.
info "fsevents@0.3.8" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "nunjucks-markdown@2.0.1" has unmet peer dependency "nunjucks@^2.3.0 || ^3.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 53.08s.
````

Снова идем в папку проекта и запускаем `gulp`:
```
C:\projects\kilogram-dev>cd projects

C:\projects\kilogram-dev\projects>cd kilogram

C:\projects\kilogram-dev\projects\kilogram>gulp
[10:18:31] Using gulpfile C:\projects\kilogram-dev\projects\kilogram\gulpfile.js
[10:18:31] Starting 'default'...
[10:18:31] Starting 'clean'...
[10:18:31] Starting 'concatcss-del'...
[10:18:31] Starting 'build-del'...
[10:18:31] Finished 'clean' after 4.95 ms
[10:18:31] Starting 'concatcss'...
[10:18:31] Finished 'concatcss' after 51 ms
[10:18:31] Starting 'template'...
[10:18:31] Starting 'images'...
[10:18:31] gulp-notify: [Kilogram] Boooya! I'm done!
[10:18:31] Finished 'template' after 120 ms
[10:18:32] Finished 'images' after 167 ms
[10:18:32] Starting 'browserSync'...
[10:18:32] Finished 'browserSync' after 12 ms
[10:18:32] Starting 'watch'...
[10:18:32] Finished 'watch' after 18 ms
[10:18:32] Finished 'default' after 267 ms
[BS] Access URLs:
 ---------------------------------
    Local: http://localhost:3000
 External: http://192.168.1.9:3000
 ---------------------------------
[BS] Serving files from: ./build
```

Хвала небесам! Квест окончен, проект успешно запустился! :star: 
Я изначально шел в папку, в которой расположен `gulpfile.js`, поэтому получился вот такой кривой путь по установке.

Определенно стоит поправить README :wink:

**Comment by dudeonthehorse** [comment]
1.1 Use ```npm install``` in repo folder

**Comment by dudeonthehorse** [comment]
В скором времени обновлю README

**Comment by LanKing** [comment]
Я бы добавил yarn, он мне лично помог, поскольку npm install не поставил все зависимости

**Comment by dudeonthehorse** [comment]
Лично я вижу, что с чистой установки NPM не подтягивает только базовый пакет Gulp. Вместо Yarn для начала, я бы предложил выяснить почему это происходит.

**Comment by enemy-senator92** [comment]
Как не крути, но npm (v5+) коряво ставит все зависимости, yarn ставит все легко и просто, где то что-то пошло не так и это уже не первый случай когда npm не собирает как нужно все, а yarn легко заводится...

**Comment by SergeyNekrasoff** [comment]
Почему-то вообще нет gulpfile.js, скачал проект, поставил все модули, где gulpfile взять?

**Comment by nosovk** [comment]
@dudeonthehorse похоже готовит новую версию и стер все - возьми просто версию на несколько коммитов раньше, до того как он все стер.

**Comment by nosovk** [comment]
или нас ждет https://github.com/dudeonthehorse/kinky

**Comment by dudeonthehorse** [comment]
https://github.com/dudeonthehorse/kilogram/issues/52
